DROP TABLE IF EXISTS superstore;

-- CREATE TABLE superstore (
    order_date TEXT,
    sales NUMERIC,
    profit NUMERIC,
    category TEXT,
    sub_category TEXT,
    region TEXT,
    segment TEXT,
    quantity INT,
    discount NUMERIC
);

-- Preview the first 10 rows to confirm the dataset loaded correctly
SELECT * FROM superstore
LIMIT 10;

-- Calculate total sales generated by the business
SELECT ROUND(SUM(sales), 2) AS total_sales 
FROM superstore;

-- Calculate total profit generated by the business
SELECT ROUND(SUM(profit), 2) AS total_profit
FROM superstore;

-- Analyse total sales by product category
SELECT category, ROUND(SUM(sales), 2) AS total_sales
FROM superstore
GROUP BY category
ORDER BY total_sales DESC;

-- Analyse total profit by category to compare with sales performance
SELECT category, ROUND(SUM(profit), 2) AS total_profit
FROM superstore
GROUP BY category
ORDER BY total_profit DESC;

-- Combining results
SELECT category, ROUND(SUM(sales), 2) AS total_sales, ROUND(SUM(profit), 2) AS total_profit
FROM superstore
GROUP BY category
ORDER BY total_profit DESC;

-- Analyse average discount by category to check if heavy discounts impact profit
SELECT category, ROUND(AVG(discount), 2) AS avg_discount
FROM superstore
GROUP BY category
ORDER BY avg_discount DESC;

ALTER TABLE superstore
ADD COLUMN order_date_clean DATE;

UPDATE superstore
SET order_date_clean = TO_DATE(order_date, 'MM/DD/YYYY');

-- Analyse monthly sales trend to identify seasonality and growth patterns
SELECT 
    DATE_TRUNC('month', order_date_clean) AS month,
    ROUND(SUM(sales), 2) AS monthly_sales
FROM superstore
GROUP BY month
ORDER BY month;

-- Analyse sales by region
SELECT 
    region,
    ROUND(SUM(sales), 2) AS total_sales,
    ROUND(SUM(profit), 2) AS total_profit
FROM superstore
GROUP BY region
ORDER BY total_sales DESC;
